[theme]
base                     = "light"
primaryColor             = "#13C9C2"
backgroundColor          = "#EEF0F5"
secondaryBackgroundColor = "#FFFFFF"
textColor                = "#1A2333"
font                     = "sans serif"

[server]
headless                 = true
enableCORS               = false
enableXsrfProtection     = true

[browser]
gatherUsageStats         = false
